# Imports

In [1]:
import pandas as pd

# Options

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns', None)

# Code

In [ ]:
dataset_source = '??'
df = pd.read_csv(dataset_source)
df.head(3)
df.shape

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,A1Cresult,diabetesMed,insulin_taken,insulin_change,other_meds,other_meds_change,Readmitted
0,2278392,50941692,Caucasian,Female,[0-10),6,25,1,1,Pediatrics-Endocrinology,41,0,1,0,0,0,50.0,NaN,NaN,1,Unknown,No,No,No,No,No,0
1,149190,24691500,Caucasian,Female,[10-20),1,1,7,3,Unknown,59,0,18,0,0,0,55.0,49.0,51.0,9,Unknown,Yes,Yes,Yes,No,No,0
2,64410,55584504,AfricanAmerican,Female,[20-30),1,1,7,2,Unknown,11,5,13,2,0,1,186.0,49.0,196.0,6,Unknown,Yes,No,No,Yes,No,0

(81176, 27)